// <auto-generated />
using InventoryTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryTracker.Migrations
{
    [DbContext(typeof(InventoryTrackerContext))]
    [Migration("20260425033048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryTracker.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Appliances"
                        });
                });

            modelBuilder.Entity("InventoryTracker.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "laptop",
                            Make = "Samsung",
                            Name = "Galaxy Book 6 Ultra",
                            Qty = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Make = "Apple",
                            Name = "IPhone 17",
                            Qty = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Ergonomic chair",
                            Make = "Herman Miller",
                            Name = "Office Chair",
                            Qty = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Wooden dining table",
                            Make = "Ikea",
                            Name = "Dining Table",
                            Qty = 5
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Double-door fridge",
                            Make = "LG",
                            Name = "Refrigerator",
                            Qty = 8
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Countertop microwave",
                            Make = "Panasonic",
                            Name = "Microwave Oven",
                            Qty = 15
                        });
                });

            modelBuilder.Entity("InventoryTracker.Models.Product", b =>
                {
                    b.HasOne("InventoryTracker.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryTracker.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
